title: Práctica 6 - genericos
author: Eduardo Brito 
email: eebritosa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Informe de la Practica 6 de la asignatura de Desarrollo de Sistemas Informaticos por Eduardo Brito
# social links
github_username:  eduardobritosan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman